server:
  port: 8090

spring:
  application:
    name: wrp-core
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://qrlistmysql.c1wc6o0agckt.ap-northeast-2.rds.amazonaws.com:3306/qrlist
      username: admin

      password: qrcodelist
      driver-class-name: com.mysql.cj.jdbc.Driver 
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: 192.168.12.173         #운영 SMTP
    port: 25      

#실루엣 연동정보
silhouette:
  url: http://172.17.4.70:8095
  key: Y2E5MDk4YTktOGE3Yy00MGIwLThjZDUtYTNhMWQ4ZTZlMGQ2

#devops API 연동 정보
devops:
  url: http://127.0.0.1:8080
  api:
    token: 0b8ad259-658d-4b7c-a4b5-b42101db4239

#메신저 연동 정보
messenger:
  url: http://192.168.56.119:8008
  
#actuator 설정
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        - "threaddump"
  #server:
    #port: 9090     

#springdoc 설정
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  use-fqn: true
  api-docs:
    groups:
      enabled: true
    path: /v3/api-docs
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**
