-- 조직 트리 뷰
CREATE VIEW view_th_dept_tree
AS
-- 1.총괄
SELECT 
	IF(HEADQ_CODE IS NULL, HEADQ_CODE, CONCAT('H_' , HEADQ_CODE)) AS DEPT_CODE1,
	'' AS DEPT_CODE2,
	'' AS DEPT_CODE3,
	HEADQ_NM  AS DEPT_NAME1,
	'' AS DEPT_NAME2,
	'' AS DEPT_NAME3
FROM 
	th_bu_dept
WHERE 
	HEADQ_CODE IN (
		SELECT 
			DISTINCT(HEADQ_CODE) 
		FROM th_dept 
		WHERE DBRN_TP_CODE=2		
			AND STR_TO_DATE(CLS_YMD,'%Y%m%d') > NOW()
			AND HEADQ_CODE IS NOT NULL 
			AND SUBHQ_CODE IS NULL
		)
UNION 
-- 2.총괄에 배속된 본부
SELECT 
	IF(A.HEADQ_CODE IS NULL, A.HEADQ_CODE, CONCAT('H_', A.HEADQ_CODE)) AS DEPT_CODE1,
	IF(A.SUBHQ_CODE IS NULL, A.SUBHQ_CODE, CONCAT('S_', A.SUBHQ_CODE)) AS DEPT_CODE2,
	'' AS DEPT_CODE3,
	(SELECT HEADQ_NM FROM th_bu_dept WHERE HEADQ_CODE=A.HEADQ_CODE) AS DEPT_NAME1,
	(SELECT HEADQ_NM FROM th_bu_dept WHERE HEADQ_CODE=A.SUBHQ_CODE) AS DEPT_NAME2,
	'' AS DEPT_NAME3
FROM 
	th_dept A		
WHERE  A.DBRN_TP_CODE=2		
	AND STR_TO_DATE(A.CLS_YMD,'%Y%m%d') > NOW()
	AND A.HEADQ_CODE IS NOT NULL 
	AND A.SUBHQ_CODE IS NOT NULL	
UNION 
-- 3. 총괄+본부에 배속된 부서
SELECT 
	IF(A.HEADQ_CODE IS NULL, A.HEADQ_CODE, CONCAT('H_' , A.HEADQ_CODE)) AS DEPT_CODE1,
	IF(A.SUBHQ_CODE IS NULL, A.SUBHQ_CODE, CONCAT('S_' , A.SUBHQ_CODE)) AS DEPT_CODE2,
	A.DBRN_CODE  AS DEPT_CODE3,
	(SELECT HEADQ_NM FROM th_bu_dept WHERE HEADQ_CODE=A.HEADQ_CODE) AS DEPT_NAME1,
	(SELECT HEADQ_NM FROM th_bu_dept WHERE HEADQ_CODE=A.SUBHQ_CODE) AS DEPT_NAME2,
	A.DBRN_ABBR_NM AS DEPT_NAME3
FROM 
	th_dept A
WHERE  A.DBRN_TP_CODE=2		
	AND STR_TO_DATE(A.CLS_YMD,'%Y%m%d') > NOW()
	AND A.HEADQ_CODE IS NOT NULL 
	AND A.SUBHQ_CODE IS NOT NULL
UNION 
-- 4. 단독 본부를 찾는 부분 (필요없을수 있음), 상위부서에 포함되나 단독 분부??인??
SELECT 
	'' AS DEPT_CODE1,
	IF(HEADQ_CODE IS NULL, HEADQ_CODE, CONCAT('S_', HEADQ_CODE)) AS DEPT_CODE2,
	'' AS DEPT_CODE3,
	'' AS DEPT_NAME1,
	HEADQ_NM  AS DEPT_NAME2,
	'' AS DEPT_NAME3
FROM 
	th_bu_dept 
WHERE HEADQ_CODE  IN (
					SELECT DISTINCT(SUBHQ_CODE)
					FROM th_dept 
					WHERE DBRN_TP_CODE=2		
						AND STR_TO_DATE(CLS_YMD,'%Y%m%d') > NOW()
						AND HEADQ_CODE IS NULL 
						AND SUBHQ_CODE IS NOT NULL
				)	
UNION
-- 5. 본부에 배속된 부서
SELECT 
	IF(A.HEADQ_CODE IS NULL, CONCAT('HX_', A.HEADQ_CODE), CONCAT('H_', A.HEADQ_CODE)) AS DEPT_CODE1,
	IF(A.SUBHQ_CODE IS NULL, A.HEADQ_CODE, CONCAT('S_', A.SUBHQ_CODE)) AS DEPT_CODE2,
	A.DBRN_CODE  AS DEPT_CODE3,
	(SELECT HEADQ_NM FROM th_bu_dept WHERE HEADQ_CODE=A.HEADQ_CODE) AS DEPT_NAME1,
	(SELECT HEADQ_NM FROM th_bu_dept WHERE HEADQ_CODE=A.SUBHQ_CODE) AS DEPT_NAME2,
	A.DBRN_ABBR_NM AS DEPT_NAME3	
FROM 
	th_dept A
WHERE 
	A.DBRN_TP_CODE=2		
	AND STR_TO_DATE(A.CLS_YMD,'%Y%m%d') > NOW()
	AND A.HEADQ_CODE IS NULL 
	AND A.SUBHQ_CODE IS NOT NULL
UNION 
-- 6. 총괄에 배속된 부서
SELECT 
	IF(A.HEADQ_CODE IS NULL, A.HEADQ_CODE, CONCAT('H_', A.HEADQ_CODE)) AS DEPT_CODE1,
	IF(A.SUBHQ_CODE IS NULL, A.SUBHQ_CODE, CONCAT('S_', A.SUBHQ_CODE)) AS DEPT_CODE2,
	A.DBRN_CODE  AS DEPT_CODE3,
	(SELECT HEADQ_NM FROM th_bu_dept WHERE HEADQ_CODE=A.HEADQ_CODE) AS DEPT_NAME1,
	(SELECT HEADQ_NM FROM th_bu_dept WHERE HEADQ_CODE=A.SUBHQ_CODE) AS DEPT_NAME2,
	A.DBRN_ABBR_NM AS DEPT_NAME3	
FROM 
	th_dept A
WHERE	
	A.DBRN_TP_CODE=2		
	AND STR_TO_DATE(A.CLS_YMD,'%Y%m%d') > NOW()
	AND A.HEADQ_CODE IS NOT NULL 
	AND A.SUBHQ_CODE IS NULL










